### ISSUE TITLE
SLVM interpretter independence and if aim is to be a strict subset of a standardized lisp such as common-lisp

### ISSUE THREAD

**Issue by hgkamath** [sl-sh-dev/sl-sh#185]
Firstly thank you to the volunteer-developers for attempting to make a lisp shell.  

I have looked at 
https://sl-sh-dev.github.io/sl-sh/sl-sh-forms.html 
That doc seems to be in the starting state, as nothing is resolved and almost all forms from sl-sh are still unimplemented. But it got me thinking. Also I am not expert enough to tell if the exhaustive list of the forms are standard or not. 

Definitions/Terms:
SL = Simple-lisp (the term seems ambiguous as to whether it refers to SL-pure or SL-SH), I'd prefer SL=SL-pure.
SL-pure = Simple Lisp without shell syntax, the lisp and its macro system
SL-SH = Simple Lisp shell which is Simple Lisp with shell syntax, that allows it to be used as a shell, login shell, and also as a shell scripting language. Shell syntax includes piping, redirections, process/job control, command invocation and the like.
SLVM-pure = Simple Lisp Virtual Machine, that interprets SL-pure
SLVM-SH = that which interprets the SL-SH in conjunction with the shell scripting additions, and which currently is, I think, your whole project. 
CL=common-lisp

This issue covers 2 points

1. SLVM-pure (simple lisp virtual machine) independence 
   - I hope the development path envisions separation of the SLVM-pure so that SL-pure can be a distinct lisp interpreter on its own. 
   - This allows SL (=SL-pure) can have its own standalone interpreter/VM byte machine that can be either run independently
   - Furthermore, if the SLVM-engine can be linked to as a library, then SL can be used as a embedded scripting language.
2. Standards compliance of the forms that SL supports
   - I hope that SL is a strict subset of CL (common-lisp)
   - If so then all code written in SL will run in a CL-interpreter and also be compile-able 
   - I guess SL may need to have a special set of forms/mechanisms to interface with the shell that only make sense to use in a shell context, so excepting those. Documentations of the list of exceptions is useful. Code can be written to factor out that which is SL-pure and that which uses shell features.
   - I am far from being a CL-expert, so I cannot tell if indeed that is already the case. It helps if the README file explicitly assures readers of that, if it is indeed the case a project goal

The above two points achieves the following
- SL won't be yet another variant of lisp which requires a user to remember how to code differently 
- All the code written in SL can be re-used in a much larger CL-ecosystem without change. 

Filing this issue for clarification, not only to me, but also maybe to your project goals.
The distinction makes 3 outputs : SL as a embeddable scripting language, standalone SL-interpreter and a SL-SH shell

**Comment by sstanfield** [comment]
Thanks for the feedback.  Your definitions/terms are pretty accurate with the exception that there is really only SLVM-pure.  The shell side of things is implemented in the shell crate (independent of the VM) and includes is own "reader" for shell syntax and manages shell functionality (job control, pipes, redirects, etc).  It would be possible to use the shell crate as a basis for another shell independent of the VM/Lisp scripting as well as build a Lisp without the shell.

I believe the docs you referenced are still built on the "legacy' version of sl-sh (the tree walker pre VM implementation but this is an area being worked on).  The current VM version has not caught up to all the previous functionality but should before long.

For point 1, yes one goal is to be an able to work as a standalone (non-shell) Lisp or as an embeddable Lisp.  It is pretty easy now to replace the "slosh" crate with a similar crate without the shell functionality if so inclined.  The VM is also built to be independent, one could take it and ditch the compiler and other parts of the project to build their own language for instance.  There is also a macro system to help bridge the gap between normal Rust functions and "builtins" the VM can call.  This has not been used (to my knowledge) as an embedded language yet but that is an explicit goal.

For point2, no it is currently not a subset of CL or another Lisp.  I have pulled from many Lisp sources, some of the newer features, like destructuring, are Clojure inspired for instance but CL was probably the heaviest early influence.  Chasing a spec is not very interesting/fun for me so I don't expect that to change.  However, it is a Lisp so building a "compat" package for CL or Scheme, etc should be possible.  It probably needs to have namespaces and proper reader macros brought back (both are legacy features not yet ported, namespaces will be one of the next things I work on).  A namespace can be used to setup an alternate environment (this would involve replacing and/or changing the semantics for a lot of functions) and reader macros may be needed to tweak the reader for another dialect (overriding some built in reader macros and adding new ones for instance).  I have started using [] and {} (like Clojure) for vectors and maps as well as ~ instead of , for backquote expansion (also taken from Clojure because I borrowed ',' is whitespace as well).  So at a surface level slosh script probably looks more like Clojure these days.  Reader macros should be able to undo this, although backquotes may be interesting.

Also, one more compatibility note, sl-sh is a Lisp1 (like Scheme or Clojure) not a Lisp2 (CL).  Which is to say functions live in the same namespace as everything else, a Lisp2 has a separate namespace for functions.  This might act as an impediment to CL compatibility although it might be possible to implement a Lisp2 on top of a Lisp1.  Personally I like the simplicity of a Lisp1, especially since some operation on functions need extra syntax/seem clunky to me in a Lisp2.

Final disclaimer, despite the fact I am working on this project I was not a Lisper before hand.  This all started as one of those silly "implement a Lisp over the weekend" things that got out of hand.  So I don't really have a single Lisp to use as a model to emulate, etc.  I have just come to appreciate Lisp in general while doing this.

**Comment by hgkamath** [comment]
Thanks for the detailed reply. 
That's good too. It's a value in itself to experiment with and try discover a combination of newer language features.
Don't let my thought in point 2 dissuade your experimentation. I was approaching the issue from code portability, creating a code-base and reusing code in various places. Perhaps compat packages are good enough

Thanks for the clarification. As question is resolved, I'll close this bug. If we have anything to add we can always continue to comment on the closed bug

**Comment by hgkamath** [comment]
Another thought just came to me : 

What if your shell scripting front-end was flexible with regard to switching to various backends ?
Then anyone could use the sl-sh shell syntax with their favorite lispX/schemeX/cljX.
backends could be cl, scheme, sci , tinylisp, nanoclj, racket etc

**Comment by sstanfield** [comment]
Swapping out backends might be viable.  Since the shell code is in it's own crate, one could (using CL for example) write some CL code that accepted input from the shell and evals it and setup a receiver on the shell side to run shell commands from the Lisp side.  Basically on shell start it would also start a CL executable to hand off CL code to with a two way channel between the processes.  Any environment that supports  eval would probably work for this.  Compiling a a CL app with SBCL for instance might make this more convenient since I believe that creates an executable that includes the compiler, image, etc (so no need to install SBCL).

Feel free to reopen and keep this open for a while if you want.  Some of your first comment should be addressed in docs somewhere as well.
